import Dummyimage from "./images/Dark.jpg";
export const DUMMY_POSTS = [
  {
    id: "1",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "2",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "3",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "4",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "5",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "6",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "7",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "8",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "9",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
  {
    id: "10",
    thumbnail: Dummyimage,
    category: "education",
    title: "yash Sachan yash Sachan yash Sachan yash Sachan",
    desc: "yash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachanyash Sachan",
    authorID: 3,
  },
];
